# Generated by Django 5.1 on 2024-10-13 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitedanswer',
            name='mark',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
