# Generated by Django 5.1 on 2024-10-09 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('shenase', models.CharField(editable=False, max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('permision', models.CharField(choices=[('pri', 'private'), ('pub', 'public')], max_length=3)),
                ('password', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('join_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_id', models.CharField(editable=False, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('send_limit', models.PositiveSmallIntegerField()),
                ('mark', models.PositiveSmallIntegerField()),
                ('late_penalty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_mark', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('contribution_type', models.CharField(choices=[('I', 'individual'), ('G', 'group')], max_length=1)),
                ('marking_type', models.CharField(choices=[('T', 'teacher'), ('J', 'judge')], max_length=1)),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.classes')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('O', 'owner'), ('T', 'Teacher'), ('M', 'mentor'), ('S', 'student')], max_length=1)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.classes')),
            ],
        ),
    ]
