# Generated by Django 5.1 on 2024-10-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bank', '0002_initial'),
        ('Classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='participents',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classes',
            name='forum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Classroom.forum'),
        ),
        migrations.AddField(
            model_name='invite',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='target_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.classes'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.forum'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.soal'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.ManyToManyField(to='Classroom.question'),
        ),
        migrations.AddField(
            model_name='scores',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.question'),
        ),
        migrations.AddField(
            model_name='scores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teams',
            field=models.ManyToManyField(to='Classroom.team'),
        ),
    ]
